### ISSUE TITLE
Plot tree in new device

### ISSUE THREAD

**Issue by meteosimon** [paytonjjones/networktree#1]
In some cases plotting a network tree in a new device fails.
I detected the problem writing a vignette: https://github.com/paytonjjones/networktree/blob/78498a9feb90d6a50b1707d5309ab66e66403ebb/vignettes/returns.Rmd#L98
which plots into png device.

However, the issue also occurs when plotting in an interactive R session, e.g.:

    library("networktree")
    set.seed(111)

    data("FXRatesCHF", package = "fxregime")
    currencies <- c("USD", "JPY", "DUR", "CNY", "INR", "GBP", "ZAR")
    returns <- fxregime::fxreturns(currencies, data = FXRatesCHF)
    returns <- na.omit(returns)

    returns$year   <- as.POSIXlt(zoo::index(returns))$year
    returns$isLeap <- (returns$year %% 4) == 0
    returns$yday   <- as.POSIXlt(zoo::index(returns))$yday
    returns$time   <- 1900 + returns$year + returns$yday / ifelse(returns$isLeap, 366, 365)

    f  <- paste(paste(currencies, collapse = " + "), "~ time")
    f  <- as.formula(f)
    tr <- networktree(f, data = returns, cor = TRUE, maxdepth = 3)

    plot(tr, type = "pcor", posCol = "#008585", negCol = "#C7522B", maximum = 1)

**Comment by paytonjjones** [comment]
This issue is fixed in commit 6086b7546252cfd1dfac9418b49c19782c541105. Let me know if you encounter any further instances.
