### ISSUE TITLE
Errors in plotting

### ISSUE THREAD

**Issue by desphua** [paytonjjones/networktree#2]
I get a weird looking plot when I tried to plot:
![image](https://user-images.githubusercontent.com/28746650/54502917-f0af7300-4967-11e9-8f49-e38bd340acaf.png)

code:
tree <- networktree(nodevars=all_var[,2:28],
                    splitvars=all_var[,c("age","Marital","Education","pride","life",
                                         "family","economy","contribute","threats","perception")],
                    type="glasso")
 plot(tree, layout="spring")

Warning messages:
1: In graphics::par(fig = gridBase::gridFIG(), mar = rep(0, 4), new = TRUE) :
  calling par(new=TRUE) with no plot
2: In doTryCatch(return(expr), name, parentenv, handler) :
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)
3: In doTryCatch(return(expr), name, parentenv, handler) :
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)

**Comment by paytonjjones** [comment]
This error should be fixed by commit 6086b7546252cfd1dfac9418b49c19782c541105. Please let me know if you encounter other instances!
