### ISSUE TITLE
installation problem due to data/dass.rda file type

### ISSUE THREAD

**Issue by parsifal9** [paytonjjones/networktree#3]
Hi Payton,
the files  tipi.rda and dass.rda are "gzip compressed data, from HPFS filesystem (OS/2, NT)."
This means that I get  the message 

Warning: file ‘dass.rda’ has magic number 'RDX3' Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = envir) :   bad restore file magic number (file may be corrupted) -- no data loaded

when trying to install networktree.
The file workaholic.rda  is "bzip2 compressed data, block size = 900k" and gives no problem.

Bye

**Comment by meteosimon** [comment]
Hi parsifal9,
This warning can occur when you try to load data saved with workspace format 3 (supported from R 3.5.0) with a R version prior to 3.5.0.
What R version are you using? see

    sessionInfo()

If your R version is prior to 3.5.0 you either have to update R or omit the data for the installation.
Please let us know, if this does not fix the issue and we will keep on searching for the bug.

Cheers
Thorsten

PS: I increased the R dependency to 3.5.0

**Comment by parsifal9** [comment]
Hi Thorsten,
yes -- I was using 3.4.4. The problem vanishes  in R 3.5.0.
Thanks
